### ISSUE TITLE
Add Discourse

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [okteto/charts#121]
I would like to painlessly deploy Discourse without the need of upgrading my account just to add yet another Helm Chart repo or manually pull the chart and deploy to Okteto Cloud.

And as usual, after I file the issue, I'll work on it and maybe do testing within Okteto Cloud if possible.

**Comment by pchico83** [comment]
Hi @AndreiJirohHaliliDev2006 
For the Okteto Catalog we are looking for application building blocks, like databases, queues, Online IDEs.
You can have the one-click deployment experience by deploying a git repo with the Discourse chart using Okteto Pipelines:
https://okteto.com/docs/cloud/deploy-from-git
