### ISSUE TITLE
docker image inlets/inlets not available

### ISSUE THREAD

**Issue by jpf-okteto** [okteto/charts#139]
https://github.com/okteto/charts/blob/262af8cdb44311642e19aeb525b6d522e95ed196/inlets/templates/deployment.yaml#L24

`inlets` Docker Hub user (https://hub.docker.com/u/inlets) no longer hosts `inlets` image.

- https://github.com/inlets/inlets-archived/commit/9826a3caea9ff875dc0522a7887b0420a024710c

**Comment by pchico83** [comment]
@rberrelleza should we remove the inlets chart from the catalog?
